"""
Contract-centric models.

These supersede the week-scoped procurement model as the *primary* product
spine. A `Contract` is a long-term agreement between a restaurant and a
vendor for a category of goods (produce / dairy / proteins / dry goods /…).
It has a term window, a pricing structure, optional itemized SKUs, and a
bag of negotiated terms (MOQ, payment terms, drop windows, auto-renewal,
exclusivity, termination fee, etc.).

`ProcurementCycle` (in `models/cycles.py`) is now logically a child of a
contract — each weekly order is executed *under* an active contract — but
we don't enforce that FK yet, because the existing weekly flow still works
contract-less. The Phase 3 lifecycle agent is what wires them together.

Why so much JSON?
~~~~~~~~~~~~~~~~~

Real foodservice contracts have wildly non-standard shapes (cost-plus,
market-tied, dead-net, tiered rebates, riders). Forcing every term into a
typed column would require 30+ Optional fields most of which are NULL on
any given contract. Instead we keep the structurally-stable fields typed
(dates, status, counterparty, category) and stash the messy long tail in
`extracted_terms`. The contract verifier UI walks the manager through the
typed fields plus the more-suspect entries in `extracted_terms`.
"""
import uuid
from datetime import date, datetime
from typing import Any, Optional

from sqlalchemy import JSON
from sqlmodel import Column, Field, SQLModel


class Contract(SQLModel, table=True):
    """One long-term contract between a restaurant and a vendor.

    Lifecycle: DRAFT → ACTIVE → EXPIRING_SOON → IN_NEGOTIATION
                                 → AWAITING_SIGNATURE → ACTIVE (renewal)
                                                      → TERMINATED / EXPIRED.
    """

    __tablename__ = "contracts"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    restaurant_profile_id: uuid.UUID = Field(
        foreign_key="restaurant_profiles.id", index=True
    )

    # Vendor on the other side. Optional because the "no contract" path
    # lets the manager pre-create a placeholder contract row that's just a
    # category + estimated terms, before a vendor is even selected.
    vendor_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="vendors.id", index=True
    )

    # Human-friendly nickname ("Sysco Produce Q3 2025"). Free-form, set by
    # the extractor or the manager.
    nickname: str

    # Maps to the existing ingredient categories used elsewhere in the app
    # (Dairy, Produce, Proteins, Dry Goods, Bakery, Frozen, Beverage,
    # Disposables). Stored as a single string for the primary category; the
    # full set of categories the contract spans lives in `category_coverage`.
    primary_category: Optional[str] = None
    category_coverage: Optional[Any] = Field(default=None, sa_column=Column(JSON))

    # ── Term window ──────────────────────────────────────────────────────
    start_date: Optional[date] = None
    end_date: Optional[date] = None
    # How many days before end_date the lifecycle agent should kick off
    # the renewal/RFP loop. 60 is a reasonable default for foodservice.
    renewal_notice_days: int = Field(default=60)

    # ── Pricing model ────────────────────────────────────────────────────
    # FIXED: every line item has a locked $/unit for the term.
    # COST_PLUS: vendor's landed cost + a fixed markup.
    # MARKET_TIED: vendor publishes a market index (CME / AMS / their own
    #              "market price") weekly/monthly; we pay that ± a spread.
    # MIXED: some line items fixed, some market-tied (very common).
    pricing_structure: str = Field(default="FIXED")

    # ── Status ───────────────────────────────────────────────────────────
    status: str = Field(default="DRAFT", index=True)

    # ── Where it came from ───────────────────────────────────────────────
    # UPLOAD_PDF: parsed from a PDF the manager uploaded.
    # MANUAL_ENTRY: the manager typed terms in.
    # DEMO_SEED: generated by /api/contracts/seed-demo for testing.
    # AGENT_NEGOTIATED: produced by the lifecycle agent in a future cycle.
    source: str = Field(default="MANUAL_ENTRY")

    # Raw text extracted from the uploaded PDF (so we can re-extract if the
    # LLM extractor improves later, without asking the user to re-upload).
    raw_text: Optional[str] = None
    raw_filename: Optional[str] = None

    # Structured-but-not-typed bag of negotiated terms. Examples of keys
    # the extractor populates today: payment_terms_days, min_order_dollars,
    # min_order_lines, delivery_window, auto_renewal, termination_fee_pct,
    # exclusivity, fuel_surcharge, broken_case_fee, volume_rebate_tiers.
    # Each value is {"value": <raw>, "needs_verification": bool, "notes": str}
    # so the verify UI knows which fields to flag.
    extracted_terms: Optional[Any] = Field(default=None, sa_column=Column(JSON))

    # Manager has reviewed the extracted terms and clicked "looks right".
    # Negotiation/renewal flows refuse to operate on un-verified contracts.
    manager_verified: bool = Field(default=False)
    verified_at: Optional[datetime] = None

    # Phase 3 lifecycle agent sets this the first time it kicks off the
    # renewal/RFP loop for this contract term — prevents duplicate outbound
    # blasts on every scheduler tick.
    renewal_cycle_started_at: Optional[datetime] = None

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


class ContractLineItem(SQLModel, table=True):
    """A single SKU/ingredient line under a contract.

    Many foodservice contracts (especially "broadline" agreements with
    Sysco/US Foods/PFG) are NOT itemized at the SKU level — they instead
    describe a pricing methodology and let the buyer pull whatever SKUs
    they need. For those, the contract has zero line items and the
    comparison agent has to look at category-level cost rather than
    per-SKU. For "schedule A"-style contracts, every SKU is a line.
    """

    __tablename__ = "contract_line_items"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    contract_id: uuid.UUID = Field(foreign_key="contracts.id", index=True)

    # Free-text name as it appears on the contract. We don't force a match
    # to the Ingredient table because contracts use vendor SKU language
    # ("Mozzarella, Low-Moisture Part-Skim, 6/5lb loaf") that's broader
    # than our recipe ingredients.
    sku_name: str
    ingredient_id: Optional[uuid.UUID] = Field(
        default=None, foreign_key="ingredients.id", index=True
    )

    pack_description: Optional[str] = None        # "6/5 lb loaf", "case of 24"
    unit_of_measure: Optional[str] = None         # "lb" / "case" / "each"

    # Pricing — both can be set when the contract caps at a fixed price OR
    # a formula ("AMS Cheese - Central US + $0.35/lb").
    fixed_price: Optional[float] = None
    price_formula: Optional[str] = None

    # Annual/monthly volume commitment the manager has agreed to, if any.
    min_volume: Optional[float] = None
    min_volume_period: Optional[str] = None       # "annual" | "monthly"

    notes: Optional[str] = None


class ContractDocument(SQLModel, table=True):
    """Raw uploaded artifact (PDF, image, etc.). Kept separate from
    `Contract` so we can attach multiple versions / riders to the same
    logical contract.
    """

    __tablename__ = "contract_documents"

    id: uuid.UUID = Field(default_factory=uuid.uuid4, primary_key=True)
    contract_id: uuid.UUID = Field(foreign_key="contracts.id", index=True)

    filename: str
    mime_type: str
    # We store raw text only — actual binary blobs land in object storage
    # in production. For the demo we keep the text and not the original
    # PDF bytes to avoid bloating Postgres.
    extracted_text: Optional[str] = None
    page_count: Optional[int] = None
    uploaded_at: datetime = Field(default_factory=datetime.utcnow)
